    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author TholutAkhyar
 */
public class DialogOkFrame extends javax.swing.JFrame {

    /**
     * Creates new form DialogOk
     */
    public DialogOkFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DialogOk_Close = new javax.swing.JLabel();
        DialogOk_Title = new javax.swing.JLabel();
        DialogOk_Button = new javax.swing.JLabel();
        DialogOk_Icon = new javax.swing.JLabel();
        DialogOk_Message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(360, 180));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(44, 47, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jPanel2.setBackground(new java.awt.Color(32, 34, 37));

        DialogOk_Close.setBackground(new java.awt.Color(32, 34, 37));
        DialogOk_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DialogOk_Close.setForeground(new java.awt.Color(255, 255, 255));
        DialogOk_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogOk_Close.setText("X");
        DialogOk_Close.setOpaque(true);
        DialogOk_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DialogOk_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DialogOk_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DialogOk_CloseMouseExited(evt);
            }
        });

        DialogOk_Title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DialogOk_Title.setForeground(new java.awt.Color(255, 255, 255));
        DialogOk_Title.setText("Title Bois");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DialogOk_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DialogOk_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DialogOk_Close, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(DialogOk_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DialogOk_Button.setBackground(new java.awt.Color(114, 137, 218));
        DialogOk_Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DialogOk_Button.setForeground(new java.awt.Color(255, 255, 255));
        DialogOk_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogOk_Button.setText("Ok");
        DialogOk_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DialogOk_Button.setMaximumSize(new java.awt.Dimension(80, 30));
        DialogOk_Button.setMinimumSize(new java.awt.Dimension(80, 30));
        DialogOk_Button.setOpaque(true);
        DialogOk_Button.setPreferredSize(new java.awt.Dimension(80, 30));
        DialogOk_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DialogOk_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DialogOk_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DialogOk_ButtonMouseExited(evt);
            }
        });

        DialogOk_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoAsk.png"))); // NOI18N

        DialogOk_Message.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DialogOk_Message.setForeground(new java.awt.Color(255, 255, 255));
        DialogOk_Message.setText("There is message bois!");
        DialogOk_Message.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(DialogOk_Icon)
                        .addGap(18, 18, 18)
                        .addComponent(DialogOk_Message, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DialogOk_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DialogOk_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DialogOk_Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DialogOk_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void MasterDialogOk(String Title, String Message, String Icon) { 
        DialogOk_Title.setText(Title);
        DialogOk_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/"+Icon)));
        DialogOk_Message.setText(Message);
        this.setVisible(true);
    }
    
    private void DialogOk_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_CloseMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DialogOk_CloseMouseClicked

    private void DialogOk_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_CloseMouseEntered
        // TODO add your handling code here:
        DialogOk_Close.setBackground(new java.awt.Color(240, 71, 71));
    }//GEN-LAST:event_DialogOk_CloseMouseEntered

    private void DialogOk_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_CloseMouseExited
        // TODO add your handling code here:
        DialogOk_Close.setBackground(new java.awt.Color(32,34,37));
    }//GEN-LAST:event_DialogOk_CloseMouseExited

    private void DialogOk_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_ButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DialogOk_ButtonMouseClicked

    private void DialogOk_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_ButtonMouseEntered
        // TODO add your handling code here:
        DialogOk_Button.setBackground(new java.awt.Color(103, 123, 196));
    }//GEN-LAST:event_DialogOk_ButtonMouseEntered

    private void DialogOk_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialogOk_ButtonMouseExited
        // TODO add your handling code here:
        DialogOk_Button.setBackground(new java.awt.Color(114, 137, 218));
    }//GEN-LAST:event_DialogOk_ButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogOkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogOkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogOkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogOkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogOkFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DialogOk_Button;
    private javax.swing.JLabel DialogOk_Close;
    private javax.swing.JLabel DialogOk_Icon;
    private javax.swing.JLabel DialogOk_Message;
    private javax.swing.JLabel DialogOk_Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
